### ISSUE TITLE
Ugly slug if pages 2 levels deep

### ISSUE THREAD

**Issue by lucaberta** [stephenou/fruitionsite#1]
Created by @edgardarascom in the mayneyao gist:
https://gist.github.com/mayneyao/b9fefc9625b76f70488e5d8c2a99315d#gistcomment-3293741

@stephenou this is amazing! That's the main thing I was missing, custom slugs, so if I want to change my system at some point, no links would ever brake!

One thing, if I go 2 levels deep into sub-pages, I still get the ugly slug:
https://fruitionsite.com/Fruition-3d694da045a745b0a36708fb5e6d09d8

Every slug must be registered somewhere right?

**Comment by darshil** [comment]
Yep, for 2 level deep sub pages you need to register the slug separately. 

This is how I am doing it: 

![Screen Shot 2020-05-08 at 9 57 27 AM](https://user-images.githubusercontent.com/12867510/81412781-5e8d9f80-9112-11ea-93ce-bc5f9cf5296e.png)

**Comment by lucaberta** [comment]
> Yep, for 2 level deep sub pages you need to register the slug separately.
> 
> This is how I am doing it:
> 
> ![Screen Shot 2020-05-08 at 9 57 27 AM](https://user-images.githubusercontent.com/12867510/81412781-5e8d9f80-9112-11ea-93ce-bc5f9cf5296e.png)

Thanks @darshil I have done the exact same thing and it works well.

I have noticed that there is an additional **?v=7bcb...** in your bookshelf Notion URL, and I wonder what that additional parameter is all about.

Shouldn't we use the clean Notion URL only in that field, and anything that comes after it should be rewritten by the script?

Thanks, Luca

**Comment by stephenou** [comment]
Thanks Luca for moving this over 🙏

> Every slug must be registered somewhere right?

Yes, it's a whitelist, regardless of how many levels deep it is.

> I have noticed that there is an additional ?v=7bcb... in your bookshelf Notion URL, and I wonder what that additional parameter is all about.

That is the view id of the collection. notion.so/1234?v=5678 means show view 5678 of collection 1234. (For those not familiar, collection is a list of blocks with the same schema, and view is a list of filter/sort/UI settings to view a collection)
