### ISSUE TITLE
Url mismatch despite latest version of worker code

### ISSUE THREAD

**Issue by wastedsummer** [stephenou/fruitionsite#114]
I am using the latest version of the worker code (with updates addressing #107 and #112 ) for a notion site hosted on cloudflare with fruition but still get `Mismatch between origin and baseUrl (dev)` when going to the site. I only changed code in the configuration. Is anyone else experiencing this issue as well? 

![Screenshot from 2021-08-18 12-53-26](https://user-images.githubusercontent.com/12030245/129886593-09057cbe-9abc-4532-bcda-7649fe60f507.png)

**Comment by Sergebell** [comment]
I have the same issue.

**Comment by haakonstorm** [comment]
Yes, same here.

**Comment by jordanurbs** [comment]
Same. This error is what displays in the Worker view on cloudflare. But on the browser it shows a completely blank page with the standard "Notion - The all-in-one..." as the page title.

**Comment by wastedsummer** [comment]
Applying changes from #117 fixes this for me.
