### ISSUE TITLE
Website shows: "Continue to external site by following the link below" message.

### ISSUE THREAD

**Issue by jjamesss1** [stephenou/fruitionsite#116]
Hey, there!

Strange thing. I used fruition for 4 different subdomains on my website, but only one shows this message after setting up everything and I can't spot the f***** difference on Notion, Cloudflare, the workers or DNS to solve it myself.

The error I'm getting is "Continue to external site by following the link below"

Website: https://cronograma.cryptotribe.la/

![image](https://user-images.githubusercontent.com/89142223/129947095-e751e446-8a83-4e86-81b7-b620e59758d8.png)

Thanks in advance.

**Comment by jjamesss1** [comment]
Thank you Harry-Yep!!

**Comment by suyu1111** [comment]
你好，我不太懂这怎么解决，包括这个网站的界面我也不太熟悉
