### ISSUE TITLE
.ge domain not working

### ISSUE THREAD

**Issue by schtinkafinga** [stephenou/fruitionsite#119]
I was trying to setup Fruition site, but it didn't seem to work out, even after doing and redoing it step by step every time. In cloudflare workers page i am getting `Mismatch between origin and baseUrl (dev).`

Thing is that It works on my another domain which is cpu.my.id, but doesn't on my main domains ending with .ge.
![image](https://user-images.githubusercontent.com/63101257/130329694-b1cd2d2b-112d-4df0-a6ea-9a68af002eff.png)
![image](https://user-images.githubusercontent.com/63101257/130329700-0edbbbe4-db04-4cb5-9584-fcbeab5fb2ee.png)

**Comment by oleh-derevianko** [comment]
[fix one](https://github.com/stephenou/fruitionsite/commit/8b1f7dcf4e593348f3ba73a345f8b99b01dfc47d)
[fix 2](https://github.com/stephenou/fruitionsite/pull/117/commits/e535ec8c59bef807757600fa14f5f9e16cb20df8)

**Comment by schtinkafinga** [comment]
> [fix one](https://github.com/stephenou/fruitionsite/commit/8b1f7dcf4e593348f3ba73a345f8b99b01dfc47d)
> [fix 2](https://github.com/stephenou/fruitionsite/pull/117/commits/e535ec8c59bef807757600fa14f5f9e16cb20df8)

Still couldn't get this to work, even after using the code from the latest `worker.js` in github :(
