### ISSUE TITLE
Website domain and subdomains got back to previous and ugly notion version after being changed with fruitionsite months ago

### ISSUE THREAD

**Issue by eusicher** [stephenou/fruitionsite#130]
Hi guys!
I have the following problme. On december 12th I created my website with Notion and then, to make it more beautiful, I bought with namecheap the domain boccadior.com and with the help of fruitionsite I changed the names of the subdomains, to make them prettier. However, some weeks ago the names got back to the previous, long and ugly notion name. How can I restore them? Thanks!
 PS attached the screenshot of the DNS and Workers screens
![Cattura1](https://user-images.githubusercontent.com/90702612/133271895-82764609-1448-459a-95f9-7cba8f301d6c.PNG)
![Cattura](https://user-images.githubusercontent.com/90702612/133271905-a27b72e5-76db-4585-94ec-e24283e6c353.PNG)

**Comment by elprotectorado** [comment]
Oh bad news, well I will try to help you. I share a link where there is a functional script (you can edit it manually), you can still generate the different sections in fruitionsite and then edit. question: does the script generated from the fruitionsite.com page not work for you? Now try modifying the script. remember to enable development mode and purge cache and then go to workers and quick edit and then implement and return clear cache and deactivate development mode.

Codigo ; https://gist.githubusercontent.com/isjair/b82595bb638891bcfafef3dd64138f79/raw/420ef78f06751ccbd7175947cec004447a4d1b2d/gistfile1.txt

![3z3roz81prekhqcy68rb](https://user-images.githubusercontent.com/36779899/133331877-7182c256-96c1-43b7-a49e-e40a01eb77ee.png)
thanks dev.to/jair

> ¡Hola tios!
> Tengo el siguiente problema. El 12 de diciembre creé mi sitio web con Notion y luego, para hacerlo más bonito, compré con namecheap el dominio boccadior.com y con la ayuda de fruitionsite cambié los nombres de los subdominios, para hacerlos más bonitos. Sin embargo, hace algunas semanas los nombres volvieron al anterior, largo y feo nombre de noción. ¿Cómo puedo restaurarlos? ¡Gracias!
> PS adjuntó la captura de pantalla de las pantallas DNS y Workers
> ![Cattura1](https://user-images.githubusercontent.com/90702612/133271895-82764609-1448-459a-95f9-7cba8f301d6c.PNG)
> ![Cattura](https://user-images.githubusercontent.com/90702612/133271905-a27b72e5-76db-4585-94ec-e24283e6c353.PNG)

**Comment by eusicher** [comment]
I will try to redo it with fruition, otherwise with your code, thanks!
