### ISSUE TITLE
Blank page again 

### ISSUE THREAD

**Issue by qrcode-generator** [stephenou/fruitionsite#133]
any ideas how to solve it ?

**Comment by elprotectorado** [comment]
show me how the error is Do you have custom script from fruitionsite? Either you entered something else manually or everything is original.



> any ideas how to solve it ?

**Comment by qrcode-generator** [comment]
> show me how the error is Do you have custom script from fruitionsite? Either you entered something else manually or everything is original.
> 
> > any ideas how to solve it ?

Its ok now , the only issue is that I still got a blank page only on Iphone 5s , On a desktop browser and on the Andrioid phone is ok 
Regards Richard

**Comment by bigansh** [comment]
Please close the issue then!
