### ISSUE TITLE
How to handle CMS?

### ISSUE THREAD

**Issue by bigansh** [stephenou/fruitionsite#134]
Hey, so I have my site up and running on [bigansh.ml](https://bigansh.ml) & I have a database of my blogs on that page. Now I want to share my blog's link with my custom domain. But the way the URLs are configured right now, it doesn't recognize it & redirects to the main page. Is there a way we can change that? How am I supposed to handle CMS?

**Comment by elprotectorado** [comment]
if I see with amazement the operation of your page. when you say you want to use the custom domain and it redirects you to the main page? is the error, currently to obtain extra functionalities you must enter them manually. but if you configure your "cms" use the url that is located in the place you want them to see. and i guess you can get wev.web / blog / status configured from fruitionsite.com

> Hey, so I have my site up and running on [bigansh.ml](https://bigansh.ml) & I have a database of my blogs on that page. Now I want to share my blog's link with my custom domain. But the way the URLs are configured right now, it doesn't recognize it & redirects to the main page. Is there a way we can change that? How am I supposed to handle CMS?

**Comment by bigansh** [comment]
I am sorry, what?

I only understood that I need to configure the URL slugs manually which I already know. I want to know if we can automate it.

**Comment by bigansh** [comment]
Alright, I figured it might be my configuration. Hence I created the config script again & then tried doing what I originally intended to do. It worked. Noice.

**Comment by elprotectorado** [comment]
@bigansh if it would be done manually but at the moment it would have to be done with something different in order to be able to do that function.
example : www.web.com/home/publicacion1

but at the moment the script works
web.com/home
web.com/publication1

sorry for not being able to help you.
