### ISSUE TITLE
Could Google Analytics be integrated in the worker script?

### ISSUE THREAD

**Issue by lucaberta** [stephenou/fruitionsite#14]
I was wondering if adding the required Google Analytics tag code could be done within this script.

Would this be something that could be interesting to have as an additional feature?

Many thanks,

Luca

**Comment by lucaberta** [comment]
To be fair, I have just found some additional information about a workaround which could be useful as a starting point:
https://www.notion.so/How-to-track-page-views-in-Notion-using-Google-Analytics-dedea65bcfc1494db5e661eb08806e2c

There is also some work here on GitHub linked to this:
https://github.com/mskims/notion-ga

Still, it uses an embedded page and would need to be added on each page, which is a lot of work.

A worker script solution would definitely be much cleaner, I would presume.

--Luca

**Comment by stephenou** [comment]
Hi Luca,

Does adding the Google Analytics Javascript in the Custom Script section work?

Thanks for helping out on the repo, btw!

**Comment by lucaberta** [comment]
> Does adding the Google Analytics Javascript in the Custom Script section work?

of course it does! I somewhat had missed the additional script part, right there at point 5 in the configuration, and very empty by default!

I just copy-pasted the script provided by Google Analytics and I am already gathering data.

A cool addition to the React app would be a simple box to ask for the UAxxxx ID and create the Google Analytics JS script in the worker script directly.

My guess is that those who have a modicum of skill will be able to hack it in by copy-pasting it directly in the workers script editor on CloudFlare, like I have just done.

Thanks for your excellent work, and I am grateful for the small help I am giving around your work!

Bye, Luca
