### ISSUE TITLE
Seems like the comment button cannot be displayed？

### ISSUE THREAD

**Issue by kaaaaai** [stephenou/fruitionsite#16]
![image](https://user-images.githubusercontent.com/30493584/83735178-93920100-a682-11ea-94e8-c1058b65e549.png)
I have turned on the comment function.
But it seems that I can’t comment on my website, and I don’t seem to see a website that can be commented in the showcase example. I don’t know if this is a bug.

**Comment by stephenou** [comment]
Hi! AFAIK even if Allow Comments is turned on, someone has to log into their Notion account in order to comment on other public pages. So this won't work on custom domain unfortunately.

**Comment by ShiinaRinne** [comment]
https://github.com/ShiinaRinne/fruitionsite
Hello! I have attempted to modify the code to indirectly implement this functionality, although it may be a little boring XD
You can take a look and see if it works.
