### ISSUE TITLE
Hiding the occasional "What's new" banner that Notion puts up

### ISSUE THREAD

**Issue by lucaberta** [stephenou/fruitionsite#2]
Created by @olamoller in the mayneyao gist:
https://gist.github.com/mayneyao/b9fefc9625b76f70488e5d8c2a99315d#gistcomment-3294291

Thanks a lot, love this script! Think one optimal thing would be if it also hides the occasional "What's new" banner that Notion puts up.

**Comment by stephenou** [comment]
Thanks Luca for moving this over 🙏

@olamoller Good catch, I haven't gotten lucky to see that banner yet. If you know what the CSS selector is for the banner, let me know or open up a PR.

I added it to https://fruitionsite.com/roadmap as well.
