### ISSUE TITLE
Notion Page Redirection via Cloudflare Worker Results in Errors [not working]

### ISSUE THREAD

**Issue by edgarsgriga** [stephenou/fruitionsite#260]
I'm using a Cloudflare Worker script to redirect my custom domain to specific Notion pages. 

When implementing, I either receive a DNS_PROBE_POSSIBLE error or a 404 status code. Testing with a basic script that returns **"Hello World" works fine**, suggesting the issue lies within the redirection script.

What could be the issue?

**Comment by abeltomy** [comment]
same issue -DNS_PROBE_FINISHED_NXDOMAIN

**Comment by d8rt8v** [comment]
Have you added an `A` record of your targt domain/subdomain to `192.0.2.0` ?

Add it, purge the cache and try again in incognito mode (or clean the browser cache too)

**Comment by edgarsgriga** [comment]
> Have you added an `A` record of your targt domain/subdomain to `192.0.2.0` ?
> 
> Add it, purge the cache and try again in incognito mode (or clean the browser cache too)

This part is unclear. as in the instructions it says: 

```
4. If you don't have any A records imported, add one with your root domain as the Name and `1.1.1.1` as the Content. Otherwise, click Continue on the DNS Record page.
    - If you are using a subdomain, add one with your subdomain as the Name and `1.1.1.1` as the Content.
```
       
In my case I've changed nameservers from my hosting dns to cloudflare and I have subdomain that I want to use.
Also, I tried now to setup name (my subdomain) and content (1.1.1.1) and toggled off 'proxied'.

now when I go to my 'mysubdomain.mydomain.com' I got this error 

```
Error 1034
Edge IP Restricted
What happened?
You've requested a page on a website that is part of the [Cloudflare](https://www.cloudflare.com/5xx-error-landing/) network. The host (mysubdomain) resolved to an IP address that the owner of the website does not have access to.

What can I do?
If you are a visitor of this website:
Please try again in a few minutes.

If you are the owner of this website:
Check your DNS records to ensure they are pointed to the IP address(es) you were assigned at registration.
```

**Comment by d8rt8v** [comment]
> > Have you added an `A` record of your targt domain/subdomain to `192.0.2.0` ?
> > Add it, purge the cache and try again in incognito mode (or clean the browser cache too)
> 
> This part is unclear. as in the instructions it says:
> 
> ```
> 4. If you don't have any A records imported, add one with your root domain as the Name and `1.1.1.1` as the Content. Otherwise, click Continue on the DNS Record page.
>     - If you are using a subdomain, add one with your subdomain as the Name and `1.1.1.1` as the Content.
> ```
> 
> In my case I've changed nameservers from my hosting dns to cloudflare and I have subdomain that I want to use. Also, I tried now to setup name (my subdomain) and content (1.1.1.1) and toggled off 'proxied'.
> 
> now when I go to my 'mysubdomain.mydomain.com' I got this error
> 
> ```
> Error 1034
> Edge IP Restricted
> What happened?
> You've requested a page on a website that is part of the [Cloudflare](https://www.cloudflare.com/5xx-error-landing/) network. The host (mysubdomain) resolved to an IP address that the owner of the website does not have access to.
> 
> What can I do?
> If you are a visitor of this website:
> Please try again in a few minutes.
> 
> If you are the owner of this website:
> Check your DNS records to ensure they are pointed to the IP address(es) you were assigned at registration.
> ```

Look for https://github.com/stephenou/fruitionsite/issues/223#issue-1523751080

**Comment by heyitsmedev** [comment]
This fixed the issue!

Thank you so much!

**Comment by edgarsgriga** [comment]
This fixed the issue!

Thank you so much!
