### ISSUE TITLE
LinkedIn banner via <script> tag

### ISSUE THREAD

**Issue by ViktorPika** [stephenou/fruitionsite#262]
I want to embed a LinkedIn banner to my Fruition site as instructed by LinkedIn. For that I need to paste the following tag:

<script src="https://platform.linkedin.com/badges/js/profile.js" async defer type="text/javascript"></script>

Can you advise where to paste the html tag? I only have access to my .js worker file in CloudFlare.

**Comment by jesenator** [comment]
paste it in the CUSTOM_SCRIPT variable, like this:

const CUSTOM_SCRIPT = "<script src="https://platform.linkedin.com/badges/js/profile.js" async defer type="text/javascript"></script>"

**Comment by ViktorPika** [comment]
Thanks @jesenator. I have that in my js file now.

Step 2 is adding the following:

`<div class="badge-base LI-profile-badge" data-locale="en_US" data-size="medium" data-theme="light" data-type="VERTICAL" data-vanity="viktorpika" data-version="v1"><a class="badge-base__link LI-simple-link" href="https://no.linkedin.com/in/viktorpika?trk=profile-badge">Viktor Pika</a></div>`

Again, I'm quite not sure where to paste HTML. Should I use CUSTOM_SCRIPT again?

**Comment by jesenator** [comment]
yeah, I would try that. The custom script variable appears to just be appended to the HTML. I think this will place the LinkedIn block at the top of your webpage, not sure how to change that if you want it elsewhere

**Comment by jesenator** [comment]
Okay, I just tried something. If you paste linkedin.com/in/viktorpika into notion and click create embed it will create this: 
![image](https://github.com/stephenou/fruitionsite/assets/32143901/c129c46a-db84-4fd5-8af6-6e88ae2f7fb6). I'm not sure what the other embed you are making will do, but this might be easier.

**Comment by ViktorPika** [comment]
Hahaha I was totally overengineering this. Thanks Jesse

**Comment by jesenator** [comment]
haha, you're welcome Viktor!
