### ISSUE TITLE
"This page is live on _____.notion.site" Banner...

### ISSUE THREAD

**Issue by jesenator** [stephenou/fruitionsite#268]
![image](https://github.com/stephenou/fruitionsite/assets/32143901/b3e405fc-8997-4ace-88f4-8171b65fac92)
This banner is present on all of my pages on my fruition site. It seems like it is also present on others' fruition sites. My only guess is that this is Notion's attempt to stop people from using things like fruition which pull notion page content and display it elsewhere. 
Any other thoughts? I'll work on some CSS code to hide it. Curious to hear other people's opinions.

**Comment by jesenator** [comment]
Here is what I got:

    /* removing 'This page is live on ____.notion.site.' banner */
    div.notion-cursor-listener > div:first-child > header:first-child > div:nth-child(2) {
        display: none !important;
    }

Seems like you can't remove divs by the text they contain in CSS but you can in Javascript. I tried briefly but couldn't get it to work. Does anyone else have experience with that? It would be a much better solution.

**Comment by raznostoronniy** [comment]
I'll keep an eye out for responses, I'd like to remove that div too.

**Comment by javinchugani** [comment]
I have the same issue too and it wasn't there till like the day before, it is super annoying, would like to sort this out asap, I've sent an email on this to @stephenou as well, let's see what happens.

**Comment by edgarsgriga** [comment]
got the same thing..

**Comment by bflack** [comment]
+1 :(

**Comment by bflack** [comment]
I noticed that the URL you get if you click "view site" is different, and does not show the banner. I'm not sure how to change that in the code since it's concatenated and I'm not fluent enough with code to parse it out, but I take it that would fix the root cause.

E.G., in my case the code is using 
`https://www.notion.so/thiswholecity/The-Best-Made-Company-Archive-3673bfb8289a4dd0933e2fac245acab3`

but the "View site" link is using
`https://thiswholecity.notion.site/The-Best-Made-Company-Archive-3673bfb8289a4dd0933e2fac245acab3`

**Comment by bflack** [comment]
> I noticed that the URL you get if you click "view site" is different, and does not show the banner. I'm not sure how to change that in the code since it's concatenated and I'm not fluent enough with code to parse it out, but I take it that would fix the root cause.
> 
> E.G., in my case the code is using `https://www.notion.so/thiswholecity/The-Best-Made-Company-Archive-3673bfb8289a4dd0933e2fac245acab3`
> 
> but the "View site" link is using `https://thiswholecity.notion.site/The-Best-Made-Company-Archive-3673bfb8289a4dd0933e2fac245acab3`

UPDATE: I found how to do it [in another issue here](https://github.com/stephenou/fruitionsite/issues/65#issuecomment-1104274343), but it doesn't seem to fix this issue, or maybe there's another spot in the code that makes the difference.

**Comment by javinchugani** [comment]
> > I noticed that the URL you get if you click "view site" is different, and does not show the banner. I'm not sure how to change that in the code since it's concatenated and I'm not fluent enough with code to parse it out, but I take it that would fix the root cause.
> > E.G., in my case the code is using `https://www.notion.so/thiswholecity/The-Best-Made-Company-Archive-3673bfb8289a4dd0933e2fac245acab3`
> > but the "View site" link is using `https://thiswholecity.notion.site/The-Best-Made-Company-Archive-3673bfb8289a4dd0933e2fac245acab3`
> 
> UPDATE: I found how to do it [in another issue here](https://github.com/stephenou/fruitionsite/issues/65#issuecomment-1104274343), but it doesn't seem to fix this issue, or maybe there's another spot in the code that makes the difference.

So it doesn't really fix the issue, right?

**Comment by jesenator** [comment]
Yeah, I think that distinction between URL formats is important

<img width="650" alt="image" src="https://github.com/stephenou/fruitionsite/assets/32143901/0b58597d-5b31-4290-9aa1-8d8f6f49da21">

Above is the cloudflare code which pulls from the notion.so/<user_name>/<page_id> and which has the "This page is live on ..." banner
When I am logged in on the web the banner shows as well:

![image](https://github.com/stephenou/fruitionsite/assets/32143901/513fcd25-ec40-447a-97ac-3c2cd63cbab0)

I think this banner is supposed to just make it clearer when editing a Notion page that is published and to view the site settings.

When I am not logged in on the web the same link automatically redetects to the <user_name>.notion.site/<page_id> link which which does not have the banner

To solve this we have to edit the code to pull from <user_name>.notion.site/<page_id> instead of how it is now.
I can work on that later this week but let me know if anyone figures it out in the mean time.

**Comment by jesenator** [comment]
Ok, so there must be another place in the code that pulls from the notion.so link instead of the <user_name>.notion.site link if that other fix doesn't solve it?

**Comment by jesenator** [comment]
https://x.com/NotionHQ/status/1734637142964629545

**Comment by bflack** [comment]
> https://x.com/NotionHQ/status/1734637142964629545

Left them a comment about it, thanks for pointing to it.

**Comment by bflack** [comment]
> Here is what I got:
> 
> ```
> /* removing 'This page is live on ____.notion.site.' banner */
> div.notion-cursor-listener > div:first-child > header:first-child > div:nth-child(2) {
>     display: none !important;
> }
> ```
> 
> Seems like you can't remove divs by the text they contain in CSS but you can in Javascript. I tried briefly but couldn't get it to work. Does anyone else have experience with that? It would be a much better solution.

This does the trick. Hopefully we can get a more direct fix too.

**Comment by bflack** [comment]
> Ok, so there must be another place in the code that pulls from the notion.so link instead of the <user_name>.notion.site link if that other fix doesn't solve it?

I changed every instance of notion.so to my username site and I still had to use the CSS fix, so not sure what the deal is.

**Comment by jesenator** [comment]
Ok for some reason the banner is gone now.... even without the CSS. I'm not sure what did it... Is it gone for anyone else?

**Comment by javinchugani** [comment]
> Ok for some reason the banner is gone now.... even without the CSS. I'm not sure what did it... Is it gone for anyone else?

Yeah, it went away for me too, I Think they sorted it out

**Comment by edgarsgriga** [comment]
For something else.

Do you guys know if there is a solution for this?

![image](https://github.com/stephenou/fruitionsite/assets/122780491/3848a851-406c-4efb-a676-a85ea44bff87)

**Comment by jesenator** [comment]
Awesome, good work team. I'll reopen if the issue returns

**Comment by GenuinelyTired** [comment]
If you make a duplicate of the page that has it it won’t have it on there yes it ducks to lose the original but after you delete it and stuff it still won’t be there!
