### ISSUE TITLE
All images are not displayed

### ISSUE THREAD

**Issue by jeeyoonhyun** [stephenou/fruitionsite#38]
All websites, including showcase websites in https://fruitionsite.com/ stopped displaying images from today + gives error 400.
It was okay until yesterday & I accessed the websites from South Korea.
The original notion links accessed from 'share website' displays images nicely.

<img width="867" alt="Screen Shot 2020-09-05 at 6 06 09 PM" src="https://user-images.githubusercontent.com/26271473/92301905-7c74ef00-efa2-11ea-9d2a-f5a0d47e215c.png">

**Comment by tortoisepro** [comment]
Yes. Something happened in the last 12-15 hours. My main website runs on Fruition script and therefore this is critical.

Need to solve this ASAP. I will be dropping a message to Stephen on mail as well.

**Comment by lucaberta** [comment]
There are been a change in how Notion treats images, and pull request #37 has already provided a fix adding one line and changing another in the worker script.

I have just implemented what @wonathanjong has implemented and it worked.

Maybe @stephenou could quickly pull in the changes on the master branch.

At any rate, if you go check the pull request, the changes are easily found and implemented on Cloudflare's worker script:
https://github.com/stephenou/fruitionsite/pull/37/commits/6fc300e091e5b97c2542f9d8e4805a07bc41a1b3

**Comment by tortoisepro** [comment]
While I can talk tech, I am not a developer. Hence could not identify the issue myself.

Thanks.

**Comment by lucaberta** [comment]
@tortoisepro I can help but for a fee. Please get in touch via email if you have an urgent need and don't mind paying someone to do the job for you.

Thanks,

Luca

**Comment by tortoisepro** [comment]
Thanks, but my tech cofounder fixed it immediately. Thanks again.

**Comment by lucaberta** [comment]
> Thanks, but my tech cofounder fixed it immediately. Thanks again.

Good, for a tech savvy person, all the indications I gave in the message above were very much sufficient to fix the issue!

But it's @wonathanjong that we should be thanking, really! 👍🏻💪🏻🙏🏻

**Comment by jeeyoonhyun** [comment]
@wonathanjong @lucaberta thanks!!!

**Comment by stephenou** [comment]
Fix is out, along with a new secret feature. See the posts below to find out :)

https://www.reddit.com/r/Notion/comments/iof0bl/fruition_20_with_dark_mode/
https://www.facebook.com/groups/notioncommunity/permalink/867209817140929
https://twitter.com/stephenou/status/1303064477005357056
