### ISSUE TITLE
Image 400 in Notion's new releases, how can I fix it?

### ISSUE THREAD

**Issue by Hexianji6275** [stephenou/fruitionsite#39]
Notion's new releases break the image hosting, how can I fix it ?

**Comment by saxoncameron** [comment]
+1   This is affecting all Fruition sites, including fruitionsite.com

**Comment by saxoncameron** [comment]
For what it's worth, it doesn't seem to be affecting Super, Hosting Potion, and other Notion-to-website platforms. Which probably means it's related to Fruition's specific approach with the Cloudflare script?

**Comment by eyoungmin** [comment]
#37

**Comment by stephenou** [comment]
Please see https://fruitionsite.com/update for update instructions.
