### ISSUE TITLE
Adding support for “Domain“ option in workspace configuration

### ISSUE THREAD

**Issue by lucaberta** [stephenou/fruitionsite#4]
In my tests, I have noticed that the Domain option found in the workspace configuration settings page is not currently supported.

<img width="683" alt="lux-screenshot0743" src="https://user-images.githubusercontent.com/5642245/81410399-f30ef680-9140-11ea-8025-09cf0a4a6615.png">

This option allows to create a longer “root“ URL by adding some text to the **notion.so/** root.

It would be nice to see this option being supported in the future.

**Comment by stephenou** [comment]
Hey Luca, do you mind elaborating what you mean, maybe with an example?

I tried using a page URL with my workspace name in it and Fruition can handle it.

![image](https://user-images.githubusercontent.com/168206/81426130-9f36ea00-910d-11ea-9d9a-ff308930562d.png)

**Comment by lucaberta** [comment]
> Hey Luca, do you mind elaborating what you mean, maybe with an example?
> 
> 
> 
> I tried using a page URL with my workspace name in it and Fruition can handle it.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/168206/81426130-9f36ea00-910d-11ea-9d9a-ff308930562d.png)
> 
> 
> 
> 

@stephenou I should have some time to test the scenario with which I ran into troubles later today, but I was in the URL prettyfication that I saw the issue pop up, and not in the main redirect, for sure.

**Comment by lucaberta** [comment]
@stephenou I have just finished doing a few more tests and I cannot reproduce the issue I faced when I opened the issue.

I am closing it at this time.
