### ISSUE TITLE
Is dark-mode overriding search functionality?

### ISSUE THREAD

**Issue by pabliqe** [stephenou/fruitionsite#54]
Hi @stephenou, I'm not sure if this is "feature or bug", but seems that Fruition latests scripts are overriding the search bar to put the dark-mode switcher.

I don't think this is a good thing since search is a pretty powerful thing for public notions.

What do you think about it?

## Header in Fruition
![Captura de Pantalla 2020-10-17 a la(s) 14 09 29](https://user-images.githubusercontent.com/1827527/96348932-a7af2b80-1082-11eb-97d9-f341f5293ee0.png)

## Header in Notion (public link)
![Captura de Pantalla 2020-10-17 a la(s) 14 09 08](https://user-images.githubusercontent.com/1827527/96348934-ac73df80-1082-11eb-9d52-0608b3cbe6cf.png)
![Captura de Pantalla 2020-10-17 a la(s) 14 09 13](https://user-images.githubusercontent.com/1827527/96348936-aed63980-1082-11eb-9e9d-6e4f98214af3.png)

**Comment by ardinusawan** [comment]
Before fruition dark mode exist search feature was already not there CMIIW. I think we need change some code to activate search feature? 🤔

**Comment by pabliqe** [comment]
> Before fruition dark mode exist search feature was already not there CMIIW. I think we need change some code to activate search feature? 🤔

Well, thats a good starting point so. First we should check if there's this limitation comes from fruition script or Notion itself. Thanks @ardinusawan

**Comment by mrdotkg** [comment]
@pabliqe No, it is not.
While uploading automatically generated worker file to cloudflare, comment [these css lines](https://github.com/stephenou/fruitionsite/blob/7f273edcd4f7ea4707663b3209b9d1eb05aac0bb/worker.js#L189) marked by orange dot, then click _Save and Deploy_
  
<img width="756" alt="Styles in worker file" src="https://user-images.githubusercontent.com/5073326/101240392-1fa9e180-3715-11eb-8058-bbb46fcb3f91.png">

### Results

_Desktop_
<img width="891" alt="desktop-notion-site" src="https://user-images.githubusercontent.com/5073326/101240543-c7271400-3715-11eb-8f70-05a8cd95d73d.png">

_Mobile_
<img width="400" alt="mobile-notion-site" src="https://user-images.githubusercontent.com/5073326/101240591-34d34000-3716-11eb-815a-c54fc5decfaf.png">

_Search_
<img width="589" alt="Screenshot 2020-12-05 at 4 25 53 PM" src="https://user-images.githubusercontent.com/5073326/101240649-a7dcb680-3716-11eb-98e7-670134cf42cb.png">

**Comment by pabliqe** [comment]
Thanks @mrdotkg , you find a great fix to it.

I'll temporary close this since it's temporarily fixed, but I wonder why this is not enabled by default.

We can work that later on a PR
