### ISSUE TITLE
"Issue with your iOS app" error

### ISSUE THREAD

**Issue by maxkufner** [stephenou/fruitionsite#55]
Hi @stephenou, thanks for creating Fruition, very happy user!

I'm getting a recurring error that I think is related to Fruition (although I've also reported it to Notion and will update accordingly).

When I access [this](https://kufner.io/Heads-I-win-Tails-you-lose-e0ac7337e95845f2a5b286f76aa347dd) URL on Safari (iOS and Mac) I get the following error (screenshots attached):

_"Hello, we've noticed an issue with your iOS app. Please delete this app and re-install it from the App Store."_

I've deleted the Notion apps and it makes no difference to the error message.

FYI - clicking directly on the URL above doesn't actually load on Safari for me (possibly a related error?). So best to access it via:

https://kufner.io/ -> "Things I'm thinking about" -> "Heads I win, Tails you lose"

Thanks for the help :)

![IMG_6848](https://user-images.githubusercontent.com/16938184/96414402-fa085d80-11e4-11eb-8688-19aaca581e3d.PNG)
<img width="1263" alt="Screenshot 2020-10-19 at 08 27 17" src="https://user-images.githubusercontent.com/16938184/96414408-faa0f400-11e4-11eb-9a20-a2c270db2541.png">

**Comment by lucaberta** [comment]
The way I see it @maxkufner is that the Notion app should just be used on the real Notion website, not on the one created by the fruition worker thur CloudFlare.

That's how I do thing with my domain. App for editing and adding content, and the official domain just used to check that everything is OK from a normal user perspective.

HTH

**Comment by maxkufner** [comment]
Thanks @lucaberta 

This issue seems to have been patched on Notion's side, so closing the issue for now.

**Comment by hamptonharrisbrown** [comment]
Hi @maxkufner -- I'm currently experiencing this same issue, so thanks for flagging.

Through some troubleshooting, I was able to conclude that the "Embed Tweet" functionality was the cause of this issue. I no longer experienced this error message/notification on mobile web once I removed the embedded tweet from my document.

Would you mind re-opening this issue? I'd love to get this looked at / fixed, so that I can leverage the "Embed Tweet" functionality. Happy to add a new request as well, but figured the context might be helpful for you.

**Comment by hamptonharrisbrown** [comment]
cc @stephenou

**Comment by marsrobertson** [comment]
![56DCA14D-D31B-4A9C-9A62-7BB75D09AE58](https://user-images.githubusercontent.com/44369284/177579261-d37739dd-8e40-4fc4-893c-0579efc41ee5.png)

Happened to me right now.

**Comment by PersistVenture** [comment]
having same issues :(

**Comment by bflack** [comment]
Just started experiencing this at https://bestmadearchive.com

**Comment by kkarakk** [comment]
Yup same problem, even if I publish a blank page with fruition I get this error.

**Comment by jayviddy** [comment]
yep same problem.  only on mobile it seems.  anyone have a fix?

**Comment by youpdidou** [comment]
Clearing my cookies seems to have solved the problem for me 🤷

**Comment by arxifythedev** [comment]
the solution I used was to comment out the MetaRewriter class and also lines these two lines at the end. it should look like this:
![IMG_1520](https://github.com/stephenou/fruitionsite/assets/69035413/79eb6379-94c6-4530-87aa-32004177e505)
![IMG_1521](https://github.com/stephenou/fruitionsite/assets/69035413/7af77ebe-c4ed-43ee-b59f-a7a52ca68bd4)

this worked for me and should work for you. this solution is not mine but i don't know who i saw it from

**Comment by chrisgrieser** [comment]
can confirm, the fix suggested from @devarxify also worked for me

**Comment by tranthaihoang** [comment]
@devarxify The way you showed it works fine, thank you
