### ISSUE TITLE
header - Top night mode toggle button misplaced and Notion Log In and Copy Link display on Mobile phone.

### ISSUE THREAD

**Issue by Kloudytics** [stephenou/fruitionsite#60]
Since yesterday, something may have changed at Notion.  We are having an issue with top bar look on mobile devices. Please see attached screenshots. It switches the place of the night vision toggle button and adds three buttons to login to notion. 

Your site has the same problem as my site, but some of the showcased sites don't have they also don't have the night/dark button so I guess, that is what causing the issue. Not sure though. Let me know if you have  a quick fix for it - like disabling the dark switch button - or if you are aware and working on it.

**Comment by ardinusawan** [comment]
![Uploading Screenshot_2020-11-09-09-34-13-641_org.mozilla.firefox.jpg…]()

Adding screenshot

**Comment by vovkazm** [comment]
+1

**Comment by eyoungmin** [comment]
+1

**Comment by emindeniz99** [comment]
I have solved it with this code  `div.notion-topbar-mobile > div:nth-child(5) { display: none !important; }`
append this to line 191

4 -> search button
5 -> more( three dot ) button , which is not exist current worker.js

https://github.com/stephenou/fruitionsite/blob/5bc77e05f2f5982e240e60484521aec30ceeda57/worker.js#L191

**Comment by vovkazm** [comment]
> I have solved it with this code `div.notion-topbar-mobile > div:nth-child(5) { display: none !important; }`
> append this to line 191
> 
> 4 -> search button
> 5 -> more( three dot ) button , which is not exist current worker.js
> 
> https://github.com/stephenou/fruitionsite/blob/5bc77e05f2f5982e240e60484521aec30ceeda57/worker.js#L191
> 
> edit: I have solved button location problem.
> I have tested it on my website [emindeniz99.com](https://emindeniz99.com/), it works, and I have opened PR.

It worked. Thanks.
Tell me how to set your favicon?

**Comment by emindeniz99** [comment]
> > I have solved it with this code `div.notion-topbar-mobile > div:nth-child(5) { display: none !important; }`
> > append this to line 191
> > 4 -> search button
> > 5 -> more( three dot ) button , which is not exist current worker.js
> > https://github.com/stephenou/fruitionsite/blob/5bc77e05f2f5982e240e60484521aec30ceeda57/worker.js#L191
> > 
> > edit: I have solved button location problem.
> > I have tested it on my website [emindeniz99.com](https://emindeniz99.com/), it works, and I have opened PR.
> 
> It worked. Thanks.
> Tell me how to set your favicon?
Glad to help. Favicon is automatically set from notion.so page icon after rendering original notion.so .js's.

**Comment by vovkazm** [comment]
> > > I have solved it with this code `div.notion-topbar-mobile > div:nth-child(5) { display: none !important; }`
> > > append this to line 191
> > > 4 -> search button
> > > 5 -> more( three dot ) button , which is not exist current worker.js
> > > https://github.com/stephenou/fruitionsite/blob/5bc77e05f2f5982e240e60484521aec30ceeda57/worker.js#L191
> > > 
> > > edit: I have solved button location problem.
> > > I have tested it on my website [emindeniz99.com](https://emindeniz99.com/), it works, and I have opened PR.
> > 
> > 
> > It worked. Thanks.
> > Tell me how to set your favicon?
> 
> Glad to help. Favicon is automatically set from notion.so page icon after rendering original notion.so .js's.

To be honest, I'm not very good at coding.
What actions need to be taken to replace the Notion icon with my icon? If it's not difficult, can you write in more detail?

**Comment by emindeniz99** [comment]
> > > > I have solved it with this code `div.notion-topbar-mobile > div:nth-child(5) { display: none !important; }`
> > > > append this to line 191
> > > > 4 -> search button
> > > > 5 -> more( three dot ) button , which is not exist current worker.js
> > > > https://github.com/stephenou/fruitionsite/blob/5bc77e05f2f5982e240e60484521aec30ceeda57/worker.js#L191
> > > > 
> > > > edit: I have solved button location problem.
> > > > I have tested it on my website [emindeniz99.com](https://emindeniz99.com/), it works, and I have opened PR.
> > > 
> > > 
> > > It worked. Thanks.
> > > Tell me how to set your favicon?
> > 
> > 
> > Glad to help. Favicon is automatically set from notion.so page icon after rendering original notion.so .js's.
> 
> To be honest, I'm not very good at coding.
> What actions need to be taken to replace the Notion icon with my icon? If it's not difficult, can you write in more detail?

You can add page icon on notion.so website. https://www.notion.so/Page-icons-covers-be694b07c6284ee3800bd71dde495981

**Comment by vovkazm** [comment]
@emindeniz99 Thank you very much

**Comment by Kloudytics** [comment]
@emindeniz99 <https://github.com/emindeniz99> Thank you very much

**Comment by Kloudytics** [comment]
Perfect it seems to be working fine now. 
Thank you

**Comment by CryptoBull2020** [comment]
not working. Any updates to resolve these issues?
