### ISSUE TITLE
Google Analytics not placed in the <head> section.

### ISSUE THREAD

**Issue by bigansh** [stephenou/fruitionsite#96]
I added the custom script for Google Analytics in the textarea provided. It added it to the page, but the data is not being shown in the GA dashboard. Can it be because it's not in the <head> section as Google wants it to be? How can I solve this?

**Comment by f1abeez** [comment]
How did you solve it? I am having the same issue.

**Comment by leoleung25** [comment]
How did you solve it? I am having the same issue.
