### ISSUE TITLE
Replace Notion Icon with our own icon?

### ISSUE THREAD

**Issue by hhimanshu** [stephenou/fruitionsite#99]
<img width="1920" alt="Screen Shot 2021-07-22 at 5 31 09 PM" src="https://user-images.githubusercontent.com/6589036/126725347-d11bf8af-48b8-4981-ad7a-9dd928c4acc6.png">

Hello my friend,

Is it possible to remove the notion icon? and replace with our own brand image?
Does it need to be paid Notion account?

Please help
Thanks

**Comment by sahil-rawat** [comment]
In my case, if I disable all these options in the notion page, the notion icon disappears
<img width="404" alt="Screenshot 2021-07-24 at 21 36 19" src="https://user-images.githubusercontent.com/53341206/126874369-7f866249-4461-4d97-ad9a-652bd9036af2.png">
See 👇🏻
<img width="1440" alt="Screenshot 2021-07-24 at 21 37 57" src="https://user-images.githubusercontent.com/53341206/126874410-e69fae45-2945-44f3-ace4-7442ddac1d31.png">

**Comment by hhimanshu** [comment]
@sahil-rawat , yes, that was the case for me as well. Thanks for your help
